#!/usr/bin/env bash
# Script to kill all running 7-highlander processes using SIGKILL signal

PIDS=$(pgrep -f 7-highlander)

if [ -n "$PIDS" ]; then
  for PID in $PIDS; do
    kill -9 "$PID"
  done
else
  echo "Process not found!"
fi

