#!/usr/bin/env bash
# This script prints numbers from 1 to 20 using while loop,
# and prints specific "bad luck" messages for numbers 4, 9, and 17 using case statement

count=1
while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((count++))
done
